### ISSUE TITLE
move to JuliaRegistries

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaRegistries/tag-bot#6]
As a part of the open-source infrastructure for Julia's registration process, this should be moved to the @JuliaRegistries org along with Registrator.jl (https://github.com/JuliaComputing/Registrator.jl/issues/126). Are there any issues with moving this, @christopher-dG? Will it break things if we move it?

**Comment by StefanKarpinski** [comment]
Registrator.jl has been move now.

**Comment by christopher-dG** [comment]
Nothing will break. I do not however have permissions to transfer the repo.

**Comment by StefanKarpinski** [comment]
Ok, lemme give you that...

**Comment by StefanKarpinski** [comment]
🎉
